services:
  - type: web
    name: jitsi-meet
    runtime: docker
    plan: free
    env: docker
    buildCommand: docker build -t jitsi-meet .
    startCommand: docker run -p 10000:80 -e ENABLE_XMPP_WEBSOCKET=0 jitsi-meet
