services:
  - type: web
    name: jitsi-meet
    runtime: docker
    plan: free
    env: docker
    buildCommand: docker build --no-cache --pull .
    startCommand: docker run -p 10000:80 -e ENABLE_XMPP_WEBSOCKET=0 jitsi-meet
